#!/usr/bin/env python3
"""Part D — run the fixed 8-question evaluation set end to end.

    uv run scripts/evaluate.py
    uv run scripts/evaluate.py --retrieval-only   # no LLM call; checks hit@k only
    uv run scripts/evaluate.py -k 5

Writes eval/results.json (full detail) and eval/results.md (the deliverable
table). The keyword/section auto-check is a hint, not a grade — the actual
"Correct?" column in results.md is filled in by hand after reading the
generated answers.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from eval.questions import QUESTIONS  # noqa: E402
from rag.config import DEFAULT_TOP_K, EVAL_DIR, REFUSAL_TEXT  # noqa: E402
from rag.embed import load_index  # noqa: E402
from rag.pipeline import answer_question  # noqa: E402

RESULTS_JSON = EVAL_DIR / "results.json"
RESULTS_MD = EVAL_DIR / "results.md"


def _hit_at_k(retrieved, expected_section: str) -> bool:
    if not expected_section:
        return True  # nothing expected to retrieve (Q8)
    return any(expected_section in r.chunk["section_path"] for r in retrieved)


def _auto_flag(answer: str, eq) -> str:
    if eq.expect_refusal:
        return "refused (expected)" if answer.strip().startswith(REFUSAL_TEXT) else "DID NOT REFUSE"
    missing = [kw for kw in eq.expected_keywords if kw.lower() not in answer.lower()]
    return "keywords present" if not missing else f"missing: {', '.join(missing)}"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-k", type=int, default=DEFAULT_TOP_K)
    parser.add_argument("--retrieval-only", action="store_true")
    args = parser.parse_args()

    index = load_index()
    EVAL_DIR.mkdir(parents=True, exist_ok=True)

    records = []
    for eq in QUESTIONS:
        result = answer_question(eq.question, index, k=args.k, call_llm=not args.retrieval_only)
        hit = _hit_at_k(result.retrieved, eq.expected_section)
        auto_flag = "n/a (retrieval-only)" if args.retrieval_only else _auto_flag(result.answer, eq)

        records.append(
            {
                "number": eq.number,
                "question": eq.question,
                "expected_section": eq.expected_section,
                "hit_at_k": hit,
                "top1_score": result.top1_score,
                "retrieved": [
                    {
                        "chunk_id": r.chunk["chunk_id"],
                        "section_path": r.chunk["section_path"],
                        "page_start": r.chunk["page_start"],
                        "page_end": r.chunk["page_end"],
                        "score": r.score,
                    }
                    for r in result.retrieved
                ],
                "prompt": result.prompt,
                "answer": result.answer,
                "refused_by": result.refused_by,
                "auto_flag": auto_flag,
            }
        )
        print(f"Q{eq.number}: hit@k={hit} refused_by={result.refused_by} auto_flag={auto_flag}")

    RESULTS_JSON.write_text(json.dumps(records, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    lines = [
        "# Evaluation results (Part D)",
        "",
        "Auto-generated by `scripts/evaluate.py`. `hit@k` / `auto_flag` are automated hints; "
        "`Correct?` and `Notes` are filled in by hand after reading each answer.",
        "",
        "| # | Question | Top-1 section (p.) | Answer | Correct? | Notes |",
        "|---|---|---|---|---|---|",
    ]
    for rec in records:
        top1 = rec["retrieved"][0] if rec["retrieved"] else None
        top1_str = (
            f"{top1['section_path'].split(' > ')[-1]} (p.{top1['page_start']})"
            if top1
            else "(none retrieved)"
        )
        answer_cell = rec["answer"].replace("\n", " ").replace("|", "\\|")
        question_cell = rec["question"].replace("|", "\\|")
        lines.append(
            f"| {rec['number']} | {question_cell} | {top1_str} | {answer_cell} | TBD | "
            f"hit@k={rec['hit_at_k']}, {rec['auto_flag']} |"
        )

    RESULTS_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\n-> {RESULTS_JSON}\n-> {RESULTS_MD}")


if __name__ == "__main__":
    main()
